### ISSUE TITLE
Sensitive content in repo

### ISSUE THREAD

**Issue by notrtx** [KStasi/ai-parser#1]
Hello from [Cexles](https://github.com/cexles) team

Please, rewrite commit history to delete sensitive data such as openai api token. 

https://github.com/KStasi/promptdefi-ai-parser/commit/a846135586d5d5257b868cada33d4ab5e7f5d174

**Comment by KStasi** [comment]
Thanks for pointing out. However, The api key was intentionally deactivated before the repo was made public, so it's not sensitive anymore
